export const photos = [
  {
    id: '1',
    title: 'Climbing the Summit',
    author: 'Clara Oswald',
    authorAvatar: 'https://i.pravatar.cc/150?img=1',
    views: '14,200',
    downloads: '4,853',
    resolution: '1920x1080',
    format: 'JPG',
    date: '12 Oct 2025',
    category: 'Latest',
    imageUrl: 'https://picsum.photos/seed/photo1/800/600',
    detailUrl: 'https://picsum.photos/seed/photo1/1920/1080'
  },
  {
    id: '2',
    title: 'Neon City Nights',
    author: 'Danny Pink',
    authorAvatar: 'https://i.pravatar.cc/150?img=2',
    views: '22,450',
    downloads: '8,901',
    resolution: '2048x1536',
    format: 'JPG',
    date: '18 Oct 2025',
    category: 'Trending',
    imageUrl: 'https://picsum.photos/seed/photo2/800/600',
    detailUrl: 'https://picsum.photos/seed/photo2/1920/1080'
  },
  {
    id: '3',
    title: 'Golden Desert Dunes',
    author: 'Rose Tyler',
    authorAvatar: 'https://i.pravatar.cc/150?img=3',
    views: '35,120',
    downloads: '12,400',
    resolution: '3840x2160',
    format: 'JPG',
    date: '20 Oct 2025',
    category: 'Most Viewed',
    imageUrl: 'https://picsum.photos/seed/photo3/800/600',
    detailUrl: 'https://picsum.photos/seed/photo3/1920/1080'
  },
  {
    id: '4',
    title: 'Mystical Forest Pathway',
    author: 'Martha Jones',
    authorAvatar: 'https://i.pravatar.cc/150?img=4',
    views: '9,800',
    downloads: '3,110',
    resolution: '1920x1200',
    format: 'JPG',
    date: '24 Oct 2025',
    category: 'Latest',
    imageUrl: 'https://picsum.photos/seed/photo4/800/600',
    detailUrl: 'https://picsum.photos/seed/photo4/1920/1080'
  },
  {
    id: '5',
    title: 'Ocean Wave Curl',
    author: 'Amy Pond',
    authorAvatar: 'https://i.pravatar.cc/150?img=5',
    views: '18,900',
    downloads: '7,430',
    resolution: '1920x1080',
    format: 'JPG',
    date: '02 Nov 2025',
    category: 'Trending',
    imageUrl: 'https://picsum.photos/seed/photo5/800/600',
    detailUrl: 'https://picsum.photos/seed/photo5/1920/1080'
  },
  {
    id: '6',
    title: 'Autumn Red Maple Leaves',
    author: 'Rory Williams',
    authorAvatar: 'https://i.pravatar.cc/150?img=6',
    views: '42,000',
    downloads: '16,250',
    resolution: '3000x2000',
    format: 'JPG',
    date: '05 Nov 2025',
    category: 'Most Viewed',
    imageUrl: 'https://picsum.photos/seed/photo6/800/600',
    detailUrl: 'https://picsum.photos/seed/photo6/1920/1080'
  },
  {
    id: '7',
    title: 'Milky Way Galaxy Arch',
    author: 'River Song',
    authorAvatar: 'https://i.pravatar.cc/150?img=7',
    views: '11,300',
    downloads: '4,150',
    resolution: '1920x1080',
    format: 'JPG',
    date: '10 Nov 2025',
    category: 'Latest',
    imageUrl: 'https://picsum.photos/seed/photo7/800/600',
    detailUrl: 'https://picsum.photos/seed/photo7/1920/1080'
  },
  {
    id: '8',
    title: 'Foggy Mountain Range',
    author: 'Donna Noble',
    authorAvatar: 'https://i.pravatar.cc/150?img=8',
    views: '27,100',
    downloads: '10,900',
    resolution: '1920x1080',
    format: 'JPG',
    date: '12 Nov 2025',
    category: 'Trending',
    imageUrl: 'https://picsum.photos/seed/photo8/800/600',
    detailUrl: 'https://picsum.photos/seed/photo8/1920/1080'
  },
  {
    id: '9',
    title: 'Architectural Spiral Stairs',
    author: 'Jack Harkness',
    authorAvatar: 'https://i.pravatar.cc/150?img=9',
    views: '54,600',
    downloads: '22,100',
    resolution: '2400x3600',
    format: 'JPG',
    date: '15 Nov 2025',
    category: 'Most Viewed',
    imageUrl: 'https://picsum.photos/seed/photo9/800/600',
    detailUrl: 'https://picsum.photos/seed/photo9/1920/1080'
  },
  {
    id: '10',
    title: 'Morning Dew on Rose',
    author: 'Sarah Jane',
    authorAvatar: 'https://i.pravatar.cc/150?img=10',
    views: '8,400',
    downloads: '2,900',
    resolution: '1920x1080',
    format: 'JPG',
    date: '20 Nov 2025',
    category: 'Latest',
    imageUrl: 'https://picsum.photos/seed/photo10/800/600',
    detailUrl: 'https://picsum.photos/seed/photo10/1920/1080'
  },
  {
    id: '11',
    title: 'Modern Architecture Glass',
    author: 'Wilfred Mott',
    authorAvatar: 'https://i.pravatar.cc/150?img=11',
    views: '16,500',
    downloads: '5,300',
    resolution: '2000x3000',
    format: 'JPG',
    date: '22 Nov 2025',
    category: 'Trending',
    imageUrl: 'https://picsum.photos/seed/photo11/800/600',
    detailUrl: 'https://picsum.photos/seed/photo11/1920/1080'
  },
  {
    id: '12',
    title: 'Icelandic Black Sand Beach',
    author: 'Mickey Smith',
    authorAvatar: 'https://i.pravatar.cc/150?img=12',
    views: '38,900',
    downloads: '15,600',
    resolution: '3840x2160',
    format: 'JPG',
    date: '25 Nov 2025',
    category: 'Most Viewed',
    imageUrl: 'https://picsum.photos/seed/photo12/800/600',
    detailUrl: 'https://picsum.photos/seed/photo12/1920/1080'
  },
  {
    id: '13',
    title: 'Street Rain Reflections',
    author: 'Jackie Tyler',
    authorAvatar: 'https://i.pravatar.cc/150?img=13',
    views: '7,100',
    downloads: '1,800',
    resolution: '1920x1080',
    format: 'JPG',
    date: '27 Nov 2025',
    category: 'Latest',
    imageUrl: 'https://picsum.photos/seed/photo13/800/600',
    detailUrl: 'https://picsum.photos/seed/photo13/1920/1080'
  },
  {
    id: '14',
    title: 'Breathtaking Lavender Fields',
    author: 'Bill Potts',
    authorAvatar: 'https://i.pravatar.cc/150?img=14',
    views: '20,100',
    downloads: '7,200',
    resolution: '1920x1080',
    format: 'JPG',
    date: '30 Nov 2025',
    category: 'Trending',
    imageUrl: 'https://picsum.photos/seed/photo14/800/600',
    detailUrl: 'https://picsum.photos/seed/photo14/1920/1080'
  },
  {
    id: '15',
    title: 'Alpine Turquoise Lake',
    author: 'Nardole',
    authorAvatar: 'https://i.pravatar.cc/150?img=15',
    views: '49,200',
    downloads: '19,800',
    resolution: '4000x2500',
    format: 'JPG',
    date: '02 Dec 2025',
    category: 'Most Viewed',
    imageUrl: 'https://picsum.photos/seed/photo15/800/600',
    detailUrl: 'https://picsum.photos/seed/photo15/1920/1080'
  },
  {
    id: '16',
    title: 'Majestic Forest Waterfall',
    author: 'Jenny',
    authorAvatar: 'https://i.pravatar.cc/150?img=16',
    views: '6,200',
    downloads: '2,100',
    resolution: '1920x1200',
    format: 'JPG',
    date: '05 Dec 2025',
    category: 'Latest',
    imageUrl: 'https://picsum.photos/seed/photo16/800/600',
    detailUrl: 'https://picsum.photos/seed/photo16/1920/1080'
  }
];

export const videos = [
  {
    id: '1',
    title: 'Big Buck Bunny Animation',
    author: 'Blender Foundation',
    authorAvatar: 'https://i.pravatar.cc/150?img=17',
    views: '45,200',
    downloads: '12,900',
    resolution: '1920x1080 (HD)',
    format: 'MP4',
    duration: '0:33',
    date: '10 Jan 2026',
    category: 'Trending',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid1/800/600'
  },
  {
    id: '2',
    title: 'Elephant Dream Project',
    author: 'Orange Open Source',
    authorAvatar: 'https://i.pravatar.cc/150?img=18',
    views: '12,400',
    downloads: '3,800',
    resolution: '1920x1080 (HD)',
    format: 'MP4',
    duration: '0:45',
    date: '15 Jan 2026',
    category: 'Latest',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid2/800/600'
  },
  {
    id: '3',
    title: 'Sintel CGI Cinematic',
    author: 'Durian Open Movie',
    authorAvatar: 'https://i.pravatar.cc/150?img=19',
    views: '88,900',
    downloads: '32,100',
    resolution: '1920x818 (Cinema)',
    format: 'MP4',
    duration: '0:52',
    date: '20 Jan 2026',
    category: 'Most Viewed',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid3/800/600'
  },
  {
    id: '4',
    title: 'Tears of Steel Sci-Fi',
    author: 'Mango Open Movie',
    authorAvatar: 'https://i.pravatar.cc/150?img=20',
    views: '54,300',
    downloads: '18,500',
    resolution: '1920x1080 (HD)',
    format: 'MP4',
    duration: '0:40',
    date: '25 Jan 2026',
    category: 'Trending',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid4/800/600'
  },
  {
    id: '5',
    title: 'Subaru Impreza Joyride',
    author: 'Vroom Media',
    authorAvatar: 'https://i.pravatar.cc/150?img=21',
    views: '9,500',
    downloads: '2,400',
    resolution: '1280x720 (720p)',
    format: 'MP4',
    duration: '0:15',
    date: '28 Jan 2026',
    category: 'Latest',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid5/800/600'
  },
  {
    id: '6',
    title: 'Epic Glacier Escape',
    author: 'Adventure Films',
    authorAvatar: 'https://i.pravatar.cc/150?img=22',
    views: '99,400',
    downloads: '45,600',
    resolution: '1920x1080 (HD)',
    format: 'MP4',
    duration: '0:15',
    date: '02 Feb 2026',
    category: 'Most Viewed',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid6/800/600'
  },
  {
    id: '7',
    title: 'Chromecast Fireplace Fire',
    author: 'Google Inc.',
    authorAvatar: 'https://i.pravatar.cc/150?img=23',
    views: '15,600',
    downloads: '4,900',
    resolution: '1920x1080 (HD)',
    format: 'MP4',
    duration: '0:30',
    date: '05 Feb 2026',
    category: 'Latest',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Fireplace.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid7/800/600'
  },
  {
    id: '8',
    title: 'Big Blazes Fire Fighting',
    author: 'Rescue Network',
    authorAvatar: 'https://i.pravatar.cc/150?img=24',
    views: '31,500',
    downloads: '9,200',
    resolution: '1280x720 (720p)',
    format: 'MP4',
    duration: '0:15',
    date: '10 Feb 2026',
    category: 'Trending',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid8/800/600'
  },
  {
    id: '9',
    title: 'Designing the Future Web',
    author: 'Tech Giant',
    authorAvatar: 'https://i.pravatar.cc/150?img=25',
    views: '110,500',
    downloads: '58,200',
    resolution: '3840x2160 (4K)',
    format: 'MP4',
    duration: '0:20',
    date: '12 Feb 2026',
    category: 'Most Viewed',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid9/800/600'
  },
  {
    id: '10',
    title: 'Sample W3Schools Bunny',
    author: 'W3Schools',
    authorAvatar: 'https://i.pravatar.cc/150?img=26',
    views: '5,100',
    downloads: '1,200',
    resolution: '320x240 (SD)',
    format: 'MP4',
    duration: '0:10',
    date: '18 Feb 2026',
    category: 'Latest',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid10/800/600'
  },
  {
    id: '11',
    title: 'For Bigger Fun Moments',
    author: 'Fun Club',
    authorAvatar: 'https://i.pravatar.cc/150?img=27',
    views: '24,100',
    downloads: '8,400',
    resolution: '1280x720 (720p)',
    format: 'MP4',
    duration: '0:15',
    date: '20 Feb 2026',
    category: 'Trending',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid11/800/600'
  },
  {
    id: '12',
    title: 'Subaru Rally Car Drift',
    author: 'Speedy Chaser',
    authorAvatar: 'https://i.pravatar.cc/150?img=28',
    views: '120,400',
    downloads: '64,100',
    resolution: '1920x1080 (HD)',
    format: 'MP4',
    duration: '0:15',
    date: '25 Feb 2026',
    category: 'Most Viewed',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
    thumbnailUrl: 'https://picsum.photos/seed/vid12/800/600'
  }
];

export const teamMembers = [
  {
    id: '1',
    name: 'John Doe',
    title: 'Founder & CEO',
    avatar: 'https://i.pravatar.cc/150?img=31',
    socials: { twitter: '#', linkedin: '#', facebook: '#' }
  },
  {
    id: '2',
    name: 'Jane Smith',
    title: 'Lead Photographer',
    avatar: 'https://i.pravatar.cc/150?img=32',
    socials: { twitter: '#', linkedin: '#', facebook: '#' }
  },
  {
    id: '3',
    name: 'Robert Johnson',
    title: 'Senior Video Editor',
    avatar: 'https://i.pravatar.cc/150?img=33',
    socials: { twitter: '#', linkedin: '#', facebook: '#' }
  },
  {
    id: '4',
    name: 'Emily Davis',
    title: 'Marketing Specialist',
    avatar: 'https://i.pravatar.cc/150?img=34',
    socials: { twitter: '#', linkedin: '#', facebook: '#' }
  }
];
